export const DEPARTMENTS = [
  { value: "CE", label: "Computer Engineering" },
  { value: "CS", label: "Computer Science" },
  { value: "IT", label: "Information Technology" },
  { value: "EXTC", label: "Electronics & Telecommunication" },
  { value: "ECS", label: "Electronics & Computer Science" },
  { value: "AIDS", label: "AI & Data Science (AIDS)" },
  { value: "AIML", label: "AI & Machine Learning (AIML)" },
  { value: "MECH", label: "Mechanical Engineering" },
  { value: "CIVIL", label: "Civil Engineering" },
  { value: "EE", label: "Electrical Engineering" },
  { value: "ETRX", label: "Electronics Engineering" },
  { value: "INST", label: "Instrumentation Engineering" },
  { value: "CHEM", label: "Chemical Engineering" },
  { value: "BIOTECH", label: "Biotechnology" },
  { value: "PROD", label: "Production Engineering" },
  { value: "BIOMED", label: "Biomedical Engineering" },
  { value: "AUTO", label: "Automobile Engineering" },
  { value: "CYBER", label: "Cyber Security" },
  { value: "IOT", label: "Internet of Things" },
  { value: "BSC_CS", label: "B.Sc. Computer Science" },
  { value: "BSC_IT", label: "B.Sc. Information Technology" },
  { value: "BSC_PHY", label: "B.Sc. Physics" },
  { value: "BSC_CHEM", label: "B.Sc. Chemistry" },
  { value: "BSC_MATH", label: "B.Sc. Mathematics" },
  { value: "BCA", label: "Bachelor of Computer Applications (BCA)" },
  { value: "BCOM", label: "Bachelor of Commerce (B.Com)" },
  { value: "BAF", label: "B.Com. Accounting & Finance (BAF)" },
  { value: "BBI", label: "B.Com. Banking & Insurance (BBI)" },
  { value: "BFM", label: "B.Com. Financial Markets (BFM)" },
  { value: "BMS", label: "Bachelor of Management Studies (BMS)" },
  { value: "BA_ECO", label: "B.A. Economics" },
  { value: "BA_PSY", label: "B.A. Psychology" },
  { value: "BA_SOC", label: "B.A. Sociology" },
  { value: "BA_LIT", label: "B.A. Literature" },
  { value: "BMM", label: "Bachelor of Mass Media (BMM / BAMMC)" },
  { value: "LLB", label: "Bachelor of Laws (LLB)" },
  { value: "BARCH", label: "Bachelor of Architecture (B.Arch)" },
  { value: "BPHARM", label: "Bachelor of Pharmacy (B.Pharm)" },
  { value: "OTHER", label: "Other" }
];
